"""create_product_catalog_table

Revision ID: 0b1d19574f66
Revises: dc7712741bb4
Create Date: 2026-07-30 10:22:17.182812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1d19574f66'
down_revision: Union[str, None] = 'dc7712741bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_inventory', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_catalog_brand'), 'product_catalog', ['brand'], unique=False)
    op.create_index(op.f('ix_product_catalog_category'), 'product_catalog', ['category'], unique=False)
    op.create_index(op.f('ix_product_catalog_id'), 'product_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_product_catalog_is_deleted'), 'product_catalog', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_product_catalog_product_id'), 'product_catalog', ['product_id'], unique=True)
    op.create_index(op.f('ix_product_catalog_product_name'), 'product_catalog', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_catalog_status'), 'product_catalog', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_catalog_status'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_product_name'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_product_id'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_is_deleted'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_id'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_category'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_brand'), table_name='product_catalog')
    op.drop_table('product_catalog')
    # ### end Alembic commands ###
