"""Add structured product identity columns

Revision ID: 1c02f80f9231
Revises: b29fb528191a
Create Date: 2026-08-19 00:13:54.087230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c02f80f9231'
down_revision: Union[str, None] = 'b29fb528191a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('gtin', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('upc', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('ean', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('cpu', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('ram', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('storage', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('color', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('size', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('style', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('author', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('edition', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('volume', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('weight', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('pack_size', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('dimensions', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'material')
    op.drop_column('product_catalog', 'dimensions')
    op.drop_column('product_catalog', 'pack_size')
    op.drop_column('product_catalog', 'weight')
    op.drop_column('product_catalog', 'volume')
    op.drop_column('product_catalog', 'edition')
    op.drop_column('product_catalog', 'isbn')
    op.drop_column('product_catalog', 'publisher')
    op.drop_column('product_catalog', 'author')
    op.drop_column('product_catalog', 'style')
    op.drop_column('product_catalog', 'size')
    op.drop_column('product_catalog', 'color')
    op.drop_column('product_catalog', 'gender')
    op.drop_column('product_catalog', 'storage')
    op.drop_column('product_catalog', 'ram')
    op.drop_column('product_catalog', 'cpu')
    op.drop_column('product_catalog', 'ean')
    op.drop_column('product_catalog', 'upc')
    op.drop_column('product_catalog', 'gtin')
    op.drop_column('product_catalog', 'variant')
    # ### end Alembic commands ###
