"""Add business features to product_catalog

Revision ID: 49551ba95741
Revises: f81d4ebdbe7e
Create Date: 2026-08-03 11:47:50.458920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49551ba95741'
down_revision: Union[str, None] = 'f81d4ebdbe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('product_model', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('launch_year', sa.Integer(), nullable=True))
    op.add_column('product_catalog', sa.Column('days_since_launch', sa.Integer(), nullable=True))
    op.add_column('product_catalog', sa.Column('product_lifecycle', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_catalog', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('product_catalog', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('product_catalog', sa.Column('historical_sales', sa.Integer(), nullable=True))
    op.add_column('product_catalog', sa.Column('profit_margin', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('product_catalog', sa.Column('supplier_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'supplier_name')
    op.drop_column('product_catalog', 'profit_margin')
    op.drop_column('product_catalog', 'historical_sales')
    op.drop_column('product_catalog', 'review_count')
    op.drop_column('product_catalog', 'average_rating')
    op.drop_column('product_catalog', 'competitor_price')
    op.drop_column('product_catalog', 'product_lifecycle')
    op.drop_column('product_catalog', 'days_since_launch')
    op.drop_column('product_catalog', 'launch_year')
    op.drop_column('product_catalog', 'product_model')
    # ### end Alembic commands ###
