"""remove unique constraint from product_id

Revision ID: 670a35d7be0f
Revises: f3babc1a2636
Create Date: 2026-07-27 22:57:43.481232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670a35d7be0f'
down_revision: Union[str, None] = 'f3babc1a2636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_product_id', table_name='products')
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.create_index('ix_products_product_id', 'products', ['product_id'], unique=True)
    # ### end Alembic commands ###
