"""migrate to retail_pricing_demand_100k dataset schema

Revision ID: 7143d4ee43fc
Revises: 9f6f867872df
Create Date: 2026-07-29 06:43:38.612225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7143d4ee43fc'
down_revision: Union[str, None] = '9f6f867872df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('region', sa.String(), nullable=True))
    op.add_column('products', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('products', sa.Column('season', sa.String(), nullable=True))
    op.add_column('products', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('price_change_pct', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('discount_pct', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('promotion_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('units_sold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('inventory_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stockout_flag', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('demand_index', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('products', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_channel'), 'products', ['channel'], unique=False)
    op.create_index(op.f('ix_products_date'), 'products', ['date'], unique=False)
    op.create_index(op.f('ix_products_region'), 'products', ['region'], unique=False)
    op.create_index(op.f('ix_products_season'), 'products', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_season'), table_name='products')
    op.drop_index(op.f('ix_products_region'), table_name='products')
    op.drop_index(op.f('ix_products_date'), table_name='products')
    op.drop_index(op.f('ix_products_channel'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.alter_column('products', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('products', 'demand_index')
    op.drop_column('products', 'stockout_flag')
    op.drop_column('products', 'inventory_level')
    op.drop_column('products', 'revenue')
    op.drop_column('products', 'units_sold')
    op.drop_column('products', 'promotion_type')
    op.drop_column('products', 'discount_pct')
    op.drop_column('products', 'price_change_pct')
    op.drop_column('products', 'current_price')
    op.drop_column('products', 'base_price')
    op.drop_column('products', 'season')
    op.drop_column('products', 'channel')
    op.drop_column('products', 'region')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'category')
    op.drop_column('products', 'date')
    # ### end Alembic commands ###
