"""create products table

Revision ID: 970db920a02f
Revises: 702612204f95
Create Date: 2026-07-27 22:37:24.996720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970db920a02f'
down_revision: Union[str, None] = '702612204f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comp_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comp_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comp_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qty_orders', sa.Integer(), nullable=True),
    sa.Column('product_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('weekend', sa.Boolean(), nullable=True),
    sa.Column('holiday', sa.Boolean(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_name'), 'products', ['category_name'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
