"""add_data_source_to_competitor_price_history

Revision ID: 9b1ac46962d0
Revises: eff29ecb6a61
Create Date: 2026-08-20 09:39:12.517515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1ac46962d0'
down_revision: Union[str, None] = 'eff29ecb6a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_price_history', sa.Column('data_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_price_history', 'data_source')
    # ### end Alembic commands ###
