"""Add CompetitorPriceHistory

Revision ID: 9f3581993828
Revises: b26d167bb2e2
Create Date: 2026-08-18 11:03:17.124275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3581993828'
down_revision: Union[str, None] = 'b26d167bb2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('competitor_product_id', sa.String(), nullable=True),
    sa.Column('competitor_url', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_price_history_competitor_name'), 'competitor_price_history', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_competitor_price_history_id'), 'competitor_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_competitor_price_history_product_id'), 'competitor_price_history', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_price_history_product_id'), table_name='competitor_price_history')
    op.drop_index(op.f('ix_competitor_price_history_id'), table_name='competitor_price_history')
    op.drop_index(op.f('ix_competitor_price_history_competitor_name'), table_name='competitor_price_history')
    op.drop_table('competitor_price_history')
    # ### end Alembic commands ###
