"""Add current_price to ProductCatalog

Revision ID: b26d167bb2e2
Revises: 49551ba95741
Create Date: 2026-08-05 15:41:30.579008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26d167bb2e2'
down_revision: Union[str, None] = '49551ba95741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_catalog', 'current_price')
    # ### end Alembic commands ###
