"""Add competitor product attributes

Revision ID: b29fb528191a
Revises: 082c167c2d92
Create Date: 2026-08-18 11:32:33.502635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29fb528191a'
down_revision: Union[str, None] = '082c167c2d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_price_history', sa.Column('competitor_product_name', sa.String(), nullable=True))
    op.add_column('competitor_price_history', sa.Column('match_confidence', sa.Integer(), nullable=True))
    op.add_column('competitor_price_history', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('competitor_price_history', sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor_price_history', 'last_checked_at')
    op.drop_column('competitor_price_history', 'is_available')
    op.drop_column('competitor_price_history', 'match_confidence')
    op.drop_column('competitor_price_history', 'competitor_product_name')
    # ### end Alembic commands ###
