"""Add product catalog fields

Revision ID: dc7712741bb4
Revises: 7143d4ee43fc
Create Date: 2026-07-30 09:37:24.368128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7712741bb4'
down_revision: Union[str, None] = '7143d4ee43fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('status', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'status')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'description')
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###
