"""Add marketplace metadata to product_catalog

Revision ID: eff29ecb6a61
Revises: 1c02f80f9231
Create Date: 2026-08-19 15:43:46.695380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff29ecb6a61'
down_revision: Union[str, None] = '1c02f80f9231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_catalog', sa.Column('marketplace_search_name', sa.String(), nullable=True))
    op.add_column('product_catalog', sa.Column('marketplace_ready', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_product_catalog_catalog_source'), 'product_catalog', ['catalog_source'], unique=False)
    op.create_index(op.f('ix_product_catalog_has_historical_demand'), 'product_catalog', ['has_historical_demand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_catalog_has_historical_demand'), table_name='product_catalog')
    op.drop_index(op.f('ix_product_catalog_catalog_source'), table_name='product_catalog')
    op.drop_column('product_catalog', 'marketplace_ready')
    op.drop_column('product_catalog', 'marketplace_search_name')
    # ### end Alembic commands ###
