"""align product schema exactly with kaggle dataset

Revision ID: f3babc1a2636
Revises: 970db920a02f
Create Date: 2026-07-27 22:41:53.133680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3babc1a2636'
down_revision: Union[str, None] = '970db920a02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_category_name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('month_year', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('volume', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('customers', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('lag_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('weekday', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('s', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('products', 'weekend',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="weekend::integer")
    op.alter_column('products', 'holiday',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="holiday::integer")
    op.drop_index('ix_products_category_name', table_name='products')
    op.create_index(op.f('ix_products_product_category_name'), 'products', ['product_category_name'], unique=False)
    op.drop_constraint('products_uploaded_by_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'season')
    op.drop_column('products', 'uploaded_by')
    op.drop_column('products', 'qty_orders')
    op.drop_column('products', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('qty_orders', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('season', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('products_uploaded_by_fkey', 'products', 'users', ['uploaded_by'], ['id'])
    op.drop_index(op.f('ix_products_product_category_name'), table_name='products')
    op.create_index('ix_products_category_name', 'products', ['category_name'], unique=False)
    op.alter_column('products', 'holiday',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('products', 'weekend',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('products', 's')
    op.drop_column('products', 'weekday')
    op.drop_column('products', 'lag_price')
    op.drop_column('products', 'total_price')
    op.drop_column('products', 'customers')
    op.drop_column('products', 'volume')
    op.drop_column('products', 'qty')
    op.drop_column('products', 'month_year')
    op.drop_column('products', 'product_category_name')
    # ### end Alembic commands ###
