"""Add new business features to products

Revision ID: f81d4ebdbe7e
Revises: 0b1d19574f66
Create Date: 2026-08-03 11:46:02.476446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81d4ebdbe7e'
down_revision: Union[str, None] = '0b1d19574f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_model', sa.String(), nullable=True))
    op.add_column('products', sa.Column('launch_year', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('days_since_launch', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('product_lifecycle', sa.String(), nullable=True))
    op.add_column('products', sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('historical_sales', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('profit_margin', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('supplier_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'supplier_name')
    op.drop_column('products', 'profit_margin')
    op.drop_column('products', 'historical_sales')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'average_rating')
    op.drop_column('products', 'competitor_price')
    op.drop_column('products', 'product_lifecycle')
    op.drop_column('products', 'days_since_launch')
    op.drop_column('products', 'launch_year')
    op.drop_column('products', 'product_model')
    # ### end Alembic commands ###
