from pydantic import BaseModel, Field, validator
from typing import Optional
from datetime import datetime
from decimal import Decimal

class ProductCatalogBase(BaseModel):
    product_name: str = Field(..., title="Product Name")
    category: Optional[str] = Field(None, title="Category")
    brand: Optional[str] = None
    description: Optional[str] = None
    
    # Pricing & Inventory
    base_price: Decimal = Field(..., description="Original Base Price")
    current_price: Optional[Decimal] = Field(None, description="Current Selling Price")
    cost_price: Optional[Decimal] = Field(None, description="Cost of Goods Sold")
    initial_inventory: int = Field(0, description="Initial Stock Level")
    
    # New Business Attributes
    product_model: Optional[str] = Field(None, title="Product Model")
    launch_year: Optional[int] = Field(None, title="Launch Year")
    days_since_launch: Optional[int] = Field(None, title="Days Since Launch")
    product_lifecycle: Optional[str] = Field(None, title="Product Lifecycle")
    competitor_price: Optional[Decimal] = Field(None, title="Competitor Price")
    average_rating: Optional[Decimal] = Field(None, title="Average Rating")
    review_count: Optional[int] = Field(None, title="Review Count")
    historical_sales: Optional[int] = Field(None, title="Historical Sales")
    profit_margin: Optional[Decimal] = Field(None, title="Profit Margin")
    supplier_name: Optional[str] = Field(None, title="Supplier Name")
    
    status: str = Field("Active", title="Status")

    @validator("base_price")
    def validate_base_price(cls, v):
        if v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("initial_inventory")
    def validate_initial_inventory(cls, v):
        if v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductCatalogCreate(ProductCatalogBase):
    # product_id acts as SKU. If not provided, it will be auto-generated by the backend.
    product_id: Optional[str] = Field(None, title="SKU")


class ProductCatalogUpdate(BaseModel):
    product_name: Optional[str] = Field(None)
    category: Optional[str] = Field(None)
    brand: Optional[str] = Field(None)
    description: Optional[str] = Field(None)
    base_price: Optional[Decimal] = Field(None)
    cost_price: Optional[Decimal] = Field(None)
    initial_inventory: Optional[int] = Field(None)
    
    product_model: Optional[str] = Field(None)
    launch_year: Optional[int] = Field(None)
    days_since_launch: Optional[int] = Field(None)
    product_lifecycle: Optional[str] = Field(None)
    competitor_price: Optional[Decimal] = Field(None)
    average_rating: Optional[Decimal] = Field(None)
    review_count: Optional[int] = Field(None)
    historical_sales: Optional[int] = Field(None)
    profit_margin: Optional[Decimal] = Field(None)
    supplier_name: Optional[str] = Field(None)
    
    status: Optional[str] = Field(None)

    @validator("base_price")
    def validate_base_price(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("initial_inventory")
    def validate_initial_inventory(cls, v):
        if v is not None and v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductCatalogInDBBase(ProductCatalogBase):
    id: int
    product_id: str
    is_deleted: bool
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class ProductCatalogOut(ProductCatalogInDBBase):
    pass
