from pydantic import BaseModel, Field, validator
from typing import Optional
from datetime import datetime
from decimal import Decimal

class ProductBase(BaseModel):
    product_name: Optional[str] = Field(None, title="Product Name")
    category: Optional[str] = Field(None, title="Category")
    brand: Optional[str] = Field(None, title="Brand")
    description: Optional[str] = Field(None, title="Description")
    
    base_price: Decimal = Field(..., title="Base Price")
    cost_price: Optional[Decimal] = Field(None, title="Cost Price")
    inventory_level: int = Field(0, title="Inventory Level")
    
    status: Optional[str] = Field("Active", title="Status")

    @validator("status", pre=True)
    def validate_status(cls, v):
        return v or "Active"

    @validator("base_price")
    def validate_base_price(cls, v):
        if v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("inventory_level")
    def validate_inventory_level(cls, v):
        if v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductCreate(ProductBase):
    # product_id acts as SKU. If not provided, it will be auto-generated by the backend.
    product_id: Optional[str] = Field(None, title="SKU")


class ProductUpdate(BaseModel):
    product_name: Optional[str] = Field(None)
    category: Optional[str] = Field(None)
    brand: Optional[str] = Field(None)
    description: Optional[str] = Field(None)
    base_price: Optional[Decimal] = Field(None)
    cost_price: Optional[Decimal] = Field(None)
    inventory_level: Optional[int] = Field(None)
    status: Optional[str] = Field(None)

    @validator("base_price")
    def validate_base_price(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("inventory_level")
    def validate_inventory_level(cls, v):
        if v is not None and v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductInDBBase(ProductBase):
    id: int
    product_id: str
    is_deleted: Optional[bool] = False
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class ProductOut(ProductInDBBase):
    current_price: Optional[Decimal] = None
    units_sold: Optional[int] = None
    revenue: Optional[Decimal] = None
    demand_index: Optional[Decimal] = None
    discount_pct: Optional[Decimal] = None
    promotion_type: Optional[str] = None
    price_change_pct: Optional[Decimal] = None
    region: Optional[str] = None
    channel: Optional[str] = None
    season: Optional[str] = None
    date: Optional[datetime] = None
