from pydantic import BaseModel, Field, validator
from typing import Optional
from datetime import datetime
from decimal import Decimal

class ProductCatalogBase(BaseModel):
    product_name: str = Field(..., title="Product Name")
    category: Optional[str] = Field(None, title="Category")
    brand: Optional[str] = Field(None, title="Brand")
    description: Optional[str] = Field(None, title="Description")
    
    base_price: Decimal = Field(..., title="Base Price")
    cost_price: Optional[Decimal] = Field(None, title="Cost Price")
    initial_inventory: int = Field(0, title="Initial Inventory")
    
    status: str = Field("Active", title="Status")

    @validator("base_price")
    def validate_base_price(cls, v):
        if v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("initial_inventory")
    def validate_initial_inventory(cls, v):
        if v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductCatalogCreate(ProductCatalogBase):
    # product_id acts as SKU. If not provided, it will be auto-generated by the backend.
    product_id: Optional[str] = Field(None, title="SKU")


class ProductCatalogUpdate(BaseModel):
    product_name: Optional[str] = Field(None)
    category: Optional[str] = Field(None)
    brand: Optional[str] = Field(None)
    description: Optional[str] = Field(None)
    base_price: Optional[Decimal] = Field(None)
    cost_price: Optional[Decimal] = Field(None)
    initial_inventory: Optional[int] = Field(None)
    status: Optional[str] = Field(None)

    @validator("base_price")
    def validate_base_price(cls, v):
        if v is not None and v <= 0:
            raise ValueError("Base price must be greater than 0")
        return v
        
    @validator("cost_price")
    def validate_cost_price(cls, v):
        if v is not None and v < 0:
            raise ValueError("Cost price cannot be negative")
        return v
        
    @validator("initial_inventory")
    def validate_initial_inventory(cls, v):
        if v is not None and v < 0:
            raise ValueError("Inventory cannot be negative")
        return v


class ProductCatalogInDBBase(ProductCatalogBase):
    id: int
    product_id: str
    is_deleted: bool
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class ProductCatalogOut(ProductCatalogInDBBase):
    pass
